### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sean1516**
Added link to https://github.com/linuxserver/docker-unifi-controller (if thats the one you use) took me some time to research the best repo for a container

### CODE REVIEW

**Comment by CCOSTAN** [comment]
Thanks for the PR, this is probably something I should have had in there before to make things easier. 
I actually use a different one.  
https://github.com/CCOSTAN/Docker_Support/blob/master/docker-compose.yaml#L132-L133

Have you seen this one?  Not sure of the differences or if it is worth it to switch.. 

Thoughts?

**Comment by sean1516** [comment]
Thanks, after looking at yours it seems to be better quality and I will be making a move also! Thanks for letting me keep the PR. I’m going to amend it now

**Comment by sean1516** [comment]
I messed up and created a new PR somehow :(

**Comment by CCOSTAN** [comment]
No worries.  I merged the other addition.  Hacktoberfest is all about learning!

**Pull request closed without merging**
